import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { Card, EmptyState, IconButton, KeyValue, Notice, PrimaryButton, ScreenTitle, SectionLabel, StatusPill, palette } from "@/components/sayless-ui";
import { useRoleSession } from "@/lib/role-session";
import { useSayLess } from "@/lib/sayless-store";

const toneFor = (status: string) => status === "ready" ? "good" : status === "disconnected" || status === "degraded" ? "danger" : status === "disabled" ? "warn" : "neutral";

export default function SubscriberKitScreen() {
  const router = useRouter();
  const { session, subscriberKit, isMinorOrUnverified, pairSubscriberKit, setKitChannelStatus, selectSubscriberKit, selectPhoneAmbient } = useSayLess();
  const { role, isAuthenticated } = useRoleSession();
  const organizer = isAuthenticated && role === "organizer";
  const bothReady = subscriberKit.paired && subscriberKit.speakerChannel.status === "ready" && subscriberKit.audienceChannel.status === "ready";
  const useKit = () => { if (selectSubscriberKit()) router.replace("/capture" as any); else Alert.alert("Duo Kit is not ready", isMinorOrUnverified ? "This meeting is using Speaker Repeat Mode, so audience capture cannot be enabled." : "Pair the kit and make both channels ready before selecting it."); };
  const channel = (kind: "speaker" | "audience", label: string, description: string, status: string, battery: number) => <Card key={kind}><View style={styles.row}><View style={styles.channelHeading}><View style={styles.channelIcon}><MaterialIcons name={kind === "speaker" ? "record-voice-over" : "groups"} size={20} color={palette.ink}/></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{label}</Text><Text style={styles.body}>{description}</Text></View></View><StatusPill label={isMinorOrUnverified && kind === "audience" ? "Disabled" : status} tone={(isMinorOrUnverified && kind === "audience" ? "warn" : toneFor(status)) as any}/></View><KeyValue label="Battery" value={`${battery}%`}/>{isMinorOrUnverified && kind === "audience" ? <Notice tone="warn">This channel cannot be enabled while the safety mode is on.</Notice> : <View style={styles.channelActions}><Pressable onPress={() => setKitChannelStatus(kind, "ready")} style={styles.textControl}><Text style={styles.textControlText}>Mark ready</Text></Pressable><Pressable onPress={() => setKitChannelStatus(kind, "disconnected")} style={styles.textControl}><Text style={[styles.textControlText, { color: palette.coral }]}>Simulate disconnect</Text></Pressable></View>}</Card>;
  if (!organizer) return <ScreenContainer className="px-5 pt-2"><ScrollView contentContainerStyle={styles.content}><ScreenTitle eyebrow="Subscriber hardware" title="Duo Kit is a host device." /><Card><EmptyState icon="lock-outline" title="Hardware controls are not shared" body="Only the organizer can pair a Duo Kit, check speaker and audience channels, select a capture source, or manage the annual hardware plan." action={<PrimaryButton label={isAuthenticated ? "Open my meetings" : "Open guest meeting"} icon={isAuthenticated ? "calendar-today" : "open-in-new"} onPress={() => router.push((isAuthenticated ? "/operations" : `/guest/${session.code}`) as any)} />} /></Card></ScrollView></ScreenContainer>;

  return <ScreenContainer className="px-5 pt-2"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <ScreenTitle eyebrow="Subscriber hardware" title="Duo Kit" action={<IconButton icon="close" label="Close microphone kit" onPress={() => router.back()}/>}/>
    <Notice tone="info">The annual prepaid kit is shown as a pairing demo. This app does not claim a live Bluetooth or USB connection in Expo Go.</Notice>
    <Card><View style={styles.deviceRow}><View style={styles.deviceMark}><MaterialIcons name="settings-input-component" size={27} color={palette.white}/></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{subscriberKit.label}</Text><Text style={styles.body}>Serial {subscriberKit.id.slice(-5)} · firmware {subscriberKit.firmware}</Text></View><StatusPill label={subscriberKit.paired ? "Paired" : "Not paired"} tone={subscriberKit.paired ? "good" : "warn"}/></View><KeyValue label="Hardware plan" value="Annual prepaid"/><KeyValue label="Kit battery" value={`${subscriberKit.batteryPercent}%`} accent={subscriberKit.batteryPercent > 25 ? palette.lime : palette.coral}/>{subscriberKit.paired ? <Notice tone="good">Pairing receipt recorded: {subscriberKit.lastReceipt}.</Notice> : <PrimaryButton label="Pair this demo kit" icon="link" onPress={pairSubscriberKit}/>}</Card>
    <SectionLabel>Channel health</SectionLabel>
    {channel("speaker", subscriberKit.speakerChannel.label, "Dedicated microphone for the main speaker.", subscriberKit.speakerChannel.status, subscriberKit.speakerChannel.batteryPercent)}
    {channel("audience", subscriberKit.audienceChannel.label, "Room microphone for audience contributions.", subscriberKit.audienceChannel.status, subscriberKit.audienceChannel.batteryPercent)}
    <Card><Text style={styles.cardTitle}>Use this source</Text><Text style={styles.body}>Say Less only selects the Duo Kit when both channels are ready and the safety rule allows audience capture.</Text>{isMinorOrUnverified ? <Notice tone="warn">Speaker Repeat Mode wins. The kit cannot override this safety rule.</Notice> : null}<KeyValue label="Preflight" value={bothReady ? "Speaker + audience ready" : "Needs attention"} accent={bothReady ? palette.lime : palette.amber}/><View style={styles.buttonGap}><PrimaryButton label="Use Duo Kit for next meeting" disabled={!bothReady || isMinorOrUnverified} icon="graphic-eq" onPress={useKit}/><PrimaryButton label="Use Phone Ambient instead" tone="outline" icon="phone-android" onPress={() => { selectPhoneAmbient(); router.replace("/capture" as any); }}/></View></Card>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { gap: 15, paddingBottom: 30 }, row: { flexDirection: "row", justifyContent: "space-between", gap: 10, alignItems: "flex-start" }, deviceRow: { flexDirection: "row", alignItems: "center", gap: 11 }, deviceMark: { width: 48, height: 48, borderRadius: 16, backgroundColor: palette.ink, alignItems: "center", justifyContent: "center" }, channelHeading: { flex: 1, flexDirection: "row", alignItems: "center", gap: 10 }, channelIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: palette.soft, alignItems: "center", justifyContent: "center" }, cardTitle: { color: palette.ink, fontSize: 17, lineHeight: 22, fontWeight: "800" }, body: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, channelActions: { flexDirection: "row", gap: 16 }, textControl: { minHeight: 32, justifyContent: "center" }, textControlText: { color: palette.blue, fontSize: 13, fontWeight: "800" }, buttonGap: { gap: 9 },
});
